@startuml
class MonoBehaviour
class Input



namespace Player {
PlayerModel -->PlayerShotManagement
PlayerModel --> Enemy.EnemyCore
PlayerPresenter --> PlayerModel
PlayerPresenter --> PlayerView
PlayerPresenter --> UI.UIView
PlayerPresenter --> .Input
PlayerShotManagement ..> Shot.IShot
PlayerShotManagement --> Shot.NormalShot
PlayerShotManagement --> Shot.LaserShot
PlayerShotManagement --> Shot.DiffusionShot
PlayerShotManagement --> Bullet.BulletFactory
PlayerShotManagement ..> Bullet.IBulletBase
PlayerShotManagement --> Bullet.BulletType
PlayerShotManagement --> Shot.ShotType

class PlayerModel
class PlayerPresenter
class PlayerShotManagement
class PlayerView
}
namespace Manager{
EnemyManager --> "many" Enemy.EnemyCore
GeneralManager --> EnemyManager
SelfDestroy --> Damage.Damage
SelfDestroy ..> Damage.IDamageApplicable


class EnemyManager
class GeneralManager
class SelfDestroy 
}

namespace Enemy{
EnemyCore ..|> Damage.IDamageApplicable
EnemyCore --> EnemyMove
EnemyCore --> Damage
EnemyPresenter --> EnemyCore
EnemyPresenter -->UI.UIView


class EnemyCore
class EnemyMove
class EnemyPresenter
}

namespace Shot{
class DiffusionShot
interface IShot
class LaserShot
class NormalShot
enum ShotType
}

namespace Bullet{
BulletDecorator ..|> IBulletBase
BulletDecorator ..> IBulletBase
BulletFactory ..|> IFactoryBase
BulletFactory --> NormalBullet
BulletFactory --> LaserBullet
BulletFactory --> DiffusionBullet
BulletFactory --> BulletType
BulletFactory ..> IBulletBase
DiffusionBullet --|> BulletDecorator
DiffusionBullet ..> IBulletBase
IFactoryBase -->BulletType
LaserBullet --|> BulletDecorator
LaserBullet ..> IBulletBase
NormalBullet ..|> IBulletBase


class BulletDecorator
class BulletFactory
enum BulletType
class DiffusionBullet
interface IBulletBase
interface IFactoryBase
class LaserBullet
class NormalBullet
}

namespace UI{
class UIView
}

namespace Damage{
IDamageApplicable -->Damage

class Damage 
interface IDamageApplicable
}
@enduml